name: probai3

channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch::pytorch=2.1
  - pytorch::pytorch-cuda=12.1
  - pyg::pyg
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - pyg::pytorch-cluster
  - pyg::pytorch-spline-conv
  - numpy=1.26.4
  - pandas>=1.1.0
  - scipy>=1.5.0
  - scikit-learn>=0.24.0
  - matplotlib<=3.4.3
  - imageio>=2.9.0
  - tqdm>=4.60.0
  - pyyaml>=5.4.0
  - pip>=21.0
  - pytest>=6.2.4
  - ase>=3.22.0
  - pip:
    - tensorboard>=2.10.0
    - pit==0.5
