
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "probai3"
version = "0.1.0"
description = "Deep Generative Models: Diffusion Models for Molecule Generation"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}